name: 01 Building Blocks

on: 
  workflow_dispatch:

jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - name: print Hello World
        run: echo "Hello World"


  echo-goodby:
    runs-on: ubuntu-latest
    steps:
      - name: print Goodbye
        run: |
            echo "I will Fail"
            exit 0
      - name: Say Goodbye
        run: echo "Goodbye"

    