name: 01 - workflow Events.

on:

    schedule: 
        - cron: '30 5 * * 1,3'
    workflow_dispatch:

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: Show trigger
              run: |
                echo "i have been triggered by ${{ github.event_name }}"

