name: 06 -contexts

on:
    push:
    workflow_dispatch:
        inputs:
            debug:
                type: boolean
                default: false
            

run-name: 06 - contexts | DEBUG - ${{ inputs.DEBUG }}

env: 
    MY_WORKFLOW_VAR: 'Workflow'
    MY_OVERWRITTEN_VAR: 'Workflow'


jobs:
    echo-data:
        runs-on: ubuntu-latest
        env:
           MY_JOB_VAR: 'job'
           MY_OVERWRITTEN_VAR: 'job' 
        steps:
            - run: |
                echo "Event name: ${{ github.event_name }}"
                echo "Ref: ${{ github.Ref }}"
                echo "SHA ${{ github.SHA }}"
                echo "Actor ${{ github.Actor }}"
                echo "Workflow ${{ github.Workflow }}"
                echo "Run ID ${{ github.run_id }}"
                echo "Run Number ${{ github.run_name }}"

            - name:  Retrieve Variables
              run: echo "${{ vars.MY_VAR}}"


              env:
                MY_OVERWRITTEN_VAR: 'step'
              
    
    echo-data2:
        runs-on: ubuntu-latest
        steps:
          - name: Print Env Variables 
            run: |
                echo "Workflow env: $MY_JOB_VAR"
                echo "Overwritten env: $MY_OVERWRITTEN_VAR"  
