name: 07-expressions

run-name: 07 - Using Expressions | DEBUG - <'ON' if the debug input is true, 'OFF' otherwise>

on:

    workflow_dispatch: 
        inputs:
            debug:
                type: boolean
                default: false

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: '[debug] print start-up data'
              if: (inputs.debug == false)
              run: |
                echo "${{ github.event_name }}"
            
            - name: Print when triggered from main
              if: (inputs.debug == true && github.ref == 'refs/heads/main' )
              run: | 
                 echo "I was triggered from main"

            - run: echo "Hello World"

        