name: 07-expressions

on:
    push:
    workflow_dispatch: 
        inputs:
            debug:
                type: boolean
                default: false

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: print start-up data
              if: (inputs.debug == false)
              run: |
                echo "${{ github.event_name }}"
            
            - name: Print when triggered from main
              if: (inputs.debug == false && github.ref == refs/heads/main )
              run: | 
                 echo "I was triggered from main"

        