name: 09-functions

on:
    pull_request:
    workflow_dispatch: 

jobs:
    echo1:
        runs-on: ubuntu-latest
        steps:
            - name: Failing Step
              id: step1
              run: |
                exit 1
            - name: I will be skipped
              if: ${{ success() }}
              run: echo "I will print if previous steps succeed."
            
            - name: I will be excute
              if: ${{ failure() }}
              run: echo "I will print if previous steps fails."

            - name: I will excute when cancelled
              if: ${{ ! cancelled() }}
              run: echo "Workflow has been cancelled"

            - name: Sleep for 20 seconds
              run: sleep 20