name: 09-functions

on:
    pull_request:
    workflow_dispatch: 

jobs:
    echo1:
        runs-on: ubuntu-latest
        steps:
            - name: Sleep for 20 seconds
              run: sleep 20
            - name:  Print PR labels
              run: |
                cat << EOF
                echo "${{toJSON( github.event.pull_request.title) }}"  
                EOF

            - name: Bug Step
              if: ${{ !cancelled() && contains(github.event.pull_request.title, 'fix')}}
              run: echo "I am a bug fix"

            - name: Failing Step
              id: step1
              run: exit 1
            - name: I will be skipped
              if: ${{ success() }}
              run: echo "I will print if previous steps succeed."
            
            - name: I will be excute
              if: ${{ failure() }}
              run: echo "I will print if previous steps fails."

            - name: I will alway excute when cancelled
              if: ${{ ! cancelled() }}
              run: echo "I will always print only when workflow is not cacelled"

            - name: I will excute when cancelled
              if: ${{  cancelled() }}
              run: echo "Workflow has been cancelled"
            




