name: 11 - Working with input

on: 
    workflow_dispatch: 
        inputs:
            dry-run:
                type: boolean
                default: false
                description: Skip deployment and only print build output

            target:
                type: environment
                required: true
                description: Which env the workflow will target

            tag:
                type: choice
                options:
                    - v1
                    - v2
                    - v3


            
            


jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: Echo vars
              run: |
                echo "Input variable: 
