name: 12 - working with output


on:
    workflow_dispatch: 
        inputs:
          build-status:
            type: choice
            options:
                - success
                - failure
            default: success


   
          build-status-check:
            type: string
            default: success
jobs:
     
    deploy:
        runs-on: ubuntu-latest
      
        if: ${{ inputs.build-status-check == 'success' }}"
        steps:
          - name: deploy
            run: echo "Deploying to production"
            