name: 16 - working Environments

on:
    workflow_dispatch: 
        inputs:
            target-env:
                type: environment
                default: statging
            

run-name: 16 - Working with Environments | env - ${{  inputs.target-env }}

jobs:
    echo:
        runs-on: ubuntu-latest
        environment: ${{ inputs.target-env  }}
        env:
            my-env-value: ${{ MY_ENV_VALUE || 'default-value' }}
        steps:
            - name: Echo vars
              run: |
                echo "Env variable: ${{ env.my-env-value}}"
        


