name: 17 artifact uploaded

on:
    push: 
    workflow_dispatch: 


jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: build my project
              run: echo "Building project"
              
            - name: upload artifact
              run: |
               mkdir -p salesforce/folder
               echo My salesforce for TME sanofi > salesforce/folder/salesforce.txt

            - uses: actions/upload-artifact@v4
              with:
                name: salesforceUpload
                path: salesforce/folder
            
            - run: ls salesforce/folder